from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class SurfaceProfile:
    material: str
    roughness: float
    temperature_c: float
    thermal_response: float


@dataclass(frozen=True)
class TactileSensorConfig:
    force_noise_n: float = 0.035
    shear_noise_n: float = 0.025
    accel_noise_m_s2: float = 0.025
    acoustic_noise: float = 0.004
    acoustic_gain: float = 950.0
    accel_slip_gain: float = 14.0
    temperature_noise_c: float = 0.04
    ambient_temperature_c: float = 24.0
    force_bias_walk_n: float = 0.001
    accel_bias_walk_m_s2: float = 0.0008
    temperature_bias_walk_c: float = 0.0005


@dataclass(frozen=True)
class TactileReading:
    normal_force_n: float
    shear_force_n: float
    acoustic_energy: float
    accel_x_m_s2: float
    accel_y_m_s2: float
    accel_z_m_s2: float
    temperature_c: float

    def as_array(self) -> np.ndarray:
        return np.array(
            [
                self.normal_force_n,
                self.shear_force_n,
                self.acoustic_energy,
                self.accel_x_m_s2,
                self.accel_y_m_s2,
                self.accel_z_m_s2,
                self.temperature_c,
            ],
            dtype=np.float32,
        )


class TactileSensorModel:
    """Synthetic multimodal tactile sensor model.

    Acoustic energy is not generated by the physics engine. It is modeled as a
    vibration proxy driven by tangential slip velocity and surface roughness.
    """

    def __init__(self, config: TactileSensorConfig | None = None) -> None:
        self.config = config or TactileSensorConfig()
        self.force_bias_n = 0.0
        self.accel_bias_m_s2 = np.zeros(3, dtype=np.float64)
        self.temperature_bias_c = 0.0

    def reset(self, rng: np.random.Generator) -> None:
        self.force_bias_n = rng.normal(0.0, self.config.force_noise_n * 0.1)
        self.accel_bias_m_s2 = rng.normal(0.0, self.config.accel_noise_m_s2 * 0.1, size=3)
        self.temperature_bias_c = rng.normal(0.0, self.config.temperature_noise_c * 0.1)

    def read(self, contact, surface: SurfaceProfile, dt: float, rng: np.random.Generator) -> TactileReading:
        cfg = self.config
        self.force_bias_n += rng.normal(0.0, cfg.force_bias_walk_n * np.sqrt(dt))
        self.accel_bias_m_s2 += rng.normal(0.0, cfg.accel_bias_walk_m_s2 * np.sqrt(dt), size=3)
        self.temperature_bias_c += rng.normal(0.0, cfg.temperature_bias_walk_c * np.sqrt(dt))

        normal_force = max(
            0.0,
            contact.normal_force_n + self.force_bias_n + rng.normal(0.0, cfg.force_noise_n),
        )
        shear_force = contact.shear_force_n + rng.normal(0.0, cfg.shear_noise_n)

        slip = contact.slip_velocity_m_s
        roughness = np.clip(surface.roughness, 0.0, 1.0)
        acoustic_signal = cfg.acoustic_gain * roughness * slip * slip
        acoustic_energy = max(0.0, acoustic_signal + rng.normal(0.0, cfg.acoustic_noise))

        vibration = cfg.accel_slip_gain * roughness * slip
        accel = np.array(
            [
                vibration + rng.normal(0.0, cfg.accel_noise_m_s2),
                0.35 * vibration + rng.normal(0.0, cfg.accel_noise_m_s2),
                rng.normal(0.0, cfg.accel_noise_m_s2),
            ],
            dtype=np.float64,
        )
        accel += self.accel_bias_m_s2

        contact_blend = min(1.0, max(0.0, normal_force / 2.0))
        temperature = (
            cfg.ambient_temperature_c * (1.0 - surface.thermal_response * contact_blend)
            + surface.temperature_c * surface.thermal_response * contact_blend
            + self.temperature_bias_c
            + rng.normal(0.0, cfg.temperature_noise_c)
        )

        return TactileReading(
            normal_force_n=float(normal_force),
            shear_force_n=float(shear_force),
            acoustic_energy=float(acoustic_energy),
            accel_x_m_s2=float(accel[0]),
            accel_y_m_s2=float(accel[1]),
            accel_z_m_s2=float(accel[2]),
            temperature_c=float(temperature),
        )

